### ISSUE TITLE
Unhelpful error message: ClassCastException when @PlanningEntityCollectionProperty is used on a shadow entity collection

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#106]
Still investigating what I configured incorrectly, but this error message is unhelpful:

```
2023-06-17 21:21:43,454 ERROR [ai.tim.mod.ord.ser.OFVRPSchedulesResource] (pool-7-thread-1) Failed solving job ID (9869e22c-469e-48ae-8941-36911bf2748f).:
 java.lang.ClassCastException: class ai.timefold.model.ofvrp.domain.Delivery
 cannot be cast to class ai.timefold.model.ofvrp.domain.Vehicle
 (ai.timefold.model.ofvrp.domain.Delivery and ai.timefold.model.ofvrp.domain.Vehicle are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @3ec2ecea)
	at ai.timefold.model.ofvrp.domain.Vehicle$Timefold$MemberAccessor$Field$deliveries.executeGetter(Unknown Source)
	at ai.timefold.solver.core.impl.domain.variable.descriptor.VariableDescriptor.getValue(VariableDescriptor.java:100)
	at ai.timefold.solver.core.impl.domain.variable.descriptor.ListVariableDescriptor.getListVariable(ListVariableDescriptor.java:98)
	at ai.timefold.solver.core.impl.domain.variable.descriptor.ListVariableDescriptor.getListSize(ListVariableDescriptor.java:118)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.lambda$countUnassignedValues$16(SolutionDescriptor.java:1034)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.lambda$visitAllEntities$9(SolutionDescriptor.java:859)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.visitAllEntities(SolutionDescriptor.java:873)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.visitAllEntities(SolutionDescriptor.java:859)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.countUnassignedValues(SolutionDescriptor.java:1033)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.countUnassignedValues(SolutionDescriptor.java:1025)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.countUninitialized(SolutionDescriptor.java:1006)
	at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.setWorkingSolution(AbstractScoreDirector.java:158)
	at ai.timefold.solver.constraint.streams.bavet.BavetConstraintStreamScoreDirector.setWorkingSolution(BavetConstraintStreamScoreDirector.java:41)
	at ai.timefold.solver.core.impl.solver.scope.SolverScope.setWorkingSolutionFromBestSolution(SolverScope.java:242)
	at ai.timefold.solver.core.impl.solver.AbstractSolver.solvingStarted(AbstractSolver.java:65)
	at ai.timefold.solver.core.impl.solver.DefaultSolver.solvingStarted(DefaultSolver.java:225)
	at ai.timefold.solver.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:192)
	at ai.timefold.solver.core.impl.solver.DefaultSolverJob.call(DefaultSolverJob.java:110)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by ge0ffrey** [comment]
With quarkus.timefold.solver.domain-access-type=REFLECTION it also fails

**Comment by ge0ffrey** [comment]
This seems to be the cause:

```

    @PlanningEntityCollectionProperty
    private List<Vehicle> vehicles;

    @PlanningEntityCollectionProperty // Should be @ProblemFactCollectionProperty because Delivery is a shadow entity, not a real entity
    @ValueRangeProvider
    private List<Delivery> deliveries;
```

Proposal A)
When `@PlanningEntityCollectionProperty` is configured on a List of a type that is a shadow entity (no genuine variables), fail fast with a clear exception.
