### ISSUE TITLE
Quarkus: ClassCastException with @ShadowVariable annotation due to ClassLoader

### ISSUE THREAD

**Issue by rsynek** [TimefoldAI/timefold-solver#117]
CCE is thrown by the `GizmoMemberAccessorImplementor` when a single getter has two @ShadowVariable annotation, each targeting a different `sourceVariableName`:

```
    @ShadowVariable(variableListenerClass = ArrivalTimeUpdatingVariableListener.class, sourceVariableName = "vehicle")
    @ShadowVariable(variableListenerClass = ArrivalTimeUpdatingVariableListener.class, sourceVariableName = "previousCustomer")
    public LocalTime getArrivalTime() {
        return arrivalTime;
    }
```

The issue is gone when a reflection-based member accessor is used via the property `-Dquarkus.timefold.solver.domain-access-type=REFLECTION`

Environment: Java 17, Quarkus 3.0.3.Final

Reproducer: https://github.com/rsynek/timefold-reproducers/tree/main/solver-issue-117

See the full stacktrace below:

```
java.lang.ClassCastException: class org.acme.vehiclerouting.domain.Customer$Timefold$MemberAccessor$Method$arrivalTime cannot be cast to class ai.timefold.solver.core.impl.domain.common.accessor.MemberAccessor (org.acme.vehiclerouting.domain.Customer$Timefold$MemberAccessor$Method$arrivalTime is in unnamed module of loader 'Timefold Gizmo SolutionCloner ClassLoader' @2aa57d8f; ai.timefold.solver.core.impl.domain.common.accessor.MemberAccessor is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @75dd0f94)
                at ai.timefold.solver.core.impl.domain.common.accessor.gizmo.GizmoMemberAccessorImplementor.createInstance(GizmoMemberAccessorImplementor.java:118)
                at ai.timefold.solver.core.impl.domain.common.accessor.gizmo.GizmoMemberAccessorImplementor.createAccessorFor(GizmoMemberAccessorImplementor.java:112)
                at ai.timefold.solver.core.impl.domain.common.accessor.gizmo.GizmoMemberAccessorFactory.buildGizmoMemberAccessor(GizmoMemberAccessorFactory.java:40)
                at ai.timefold.solver.core.impl.domain.common.accessor.MemberAccessorFactory.buildMemberAccessor(MemberAccessorFactory.java:38)
                at ai.timefold.solver.core.impl.domain.common.accessor.MemberAccessorFactory.lambda$buildAndCacheMemberAccessor$0(MemberAccessorFactory.java:125)
                at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
                at ai.timefold.solver.core.impl.domain.common.accessor.MemberAccessorFactory.buildAndCacheMemberAccessor(MemberAccessorFactory.java:124)
                at ai.timefold.solver.core.impl.domain.entity.descriptor.EntityDescriptor.processPlanningVariableAnnotation(EntityDescriptor.java:240)
                at ai.timefold.solver.core.impl.domain.entity.descriptor.EntityDescriptor.processAnnotations(EntityDescriptor.java:155)
                at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.buildSolutionDescriptor(SolutionDescriptor.java:107)
                at ai.timefold.solver.core.impl.solver.DefaultSolverFactory.buildSolutionDescriptor(DefaultSolverFactory.java:148)
                at ai.timefold.solver.core.impl.solver.DefaultSolverFactory.<init>(DefaultSolverFactory.java:70)
                at ai.timefold.solver.core.api.solver.SolverFactory.create(SolverFactory.java:106)
                at ai.timefold.solver.quarkus.bean.DefaultTimefoldBeanProvider.solverFactory(DefaultTimefoldBeanProvider.java:46)
                at ai.timefold.solver.quarkus.bean.DefaultTimefoldBeanProvider_ProducerMethod_solverFactory_5706de706f4c57c0ea21f6c077f050d9d713cf51_Bean.doCreate(Unknown Source)
```

**Workaround**

In application.properties add:

`quarkus.timefold.solver.domain-access-type=REFLECTION`

**Comment by ShadowVariable** [comment]
hello!

**Comment by ge0ffrey** [comment]
If we get @PlanningVariable and @PlanningEntity in here too, it's party.

**Comment by ge0ffrey** [comment]
Fix from discussion with lukas:

MemberAccessorFactory line 95 should do:
```
private final GizmoClassLoader gizmoClassLoader = new GizmoClassLoader(getClass().getClassLoader());
```
And GizmoClassLoader should do
```
public GizmoClassLoader(ClassLoader classLoader) {
    super(classLoader);
}
```
