### ISSUE TITLE
Time spent termination quarkus property ignored in Quarkus environment?

### ISSUE THREAD

**Issue by mcimbora** [TimefoldAI/timefold-solver#269]
Hi, I'm using solver version 1.2.0. I've defined the following property in quarkus application.properties:
```
quarkus.timefold.benchmark.solver.termination.spent-limit=3s
```

Yet I've got an error indicating the property `quarkus.timefold.benchmark.solver.termination.spent-limit` is undefined.
```
Caused by: java.lang.IllegalStateException: At least one of the properties quarkus.timefold.benchmark.solver.termination.spent-limit, quarkus.timefold.benchmark.solver.termination.best-score-limit, quarkus.timefold.benchmark.solver.termination.unimproved-spent-limit is required if termination is not configured in the inherited solver benchmark config and solverBenchmarkBluePrint is used.
	at ai.timefold.solver.benchmark.quarkus.TimefoldBenchmarkRecorder.updateBenchmarkConfigWithRuntimeProperties(TimefoldBenchmarkRecorder.java:71)
	at ai.timefold.solver.benchmark.quarkus.TimefoldBenchmarkRecorder.lambda$benchmarkConfigSupplier$0(TimefoldBenchmarkRecorder.java:28)
	at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:129)
	at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:126)
	at ai.timefold.solver.benchmark.config.PlannerBenchmarkConfig_efcd57280ef559ac2ed5ea7649ad8103ac8f9326_Synthetic_Bean.createSynthetic(Unknown Source)
	... 38 more
```
&nbsp;
Expected behavior:
Time spent termination configured using `quarkus.timefold.benchmark.solver.termination.spent-limit` property is applied.

**Comment by triceo** [comment]
Orbit reproducer commit ID: 191a772fcd6f8e010c3e284990173a4ae07d1bac
