### ISSUE TITLE
Enable PICKED_MOVE benchmark statistics leads to IllegalArgumentException during report generation

### ISSUE THREAD

**Issue by jason076** [TimefoldAI/timefold-solver#360]
**Describe the bug**
Enabling the benchmark options ` <singleStatisticType>PICKED_MOVE_TYPE_BEST_SCORE_DIFF</singleStatisticType>` or
           ` <singleStatisticType>PICKED_MOVE_TYPE_STEP_SCORE_DIFF</singleStatisticType>` with cartesian product swap move in place leads to an IllegalAgrumentException.

```
java.lang.IllegalArgumentException: The scoreString (SpecialJob.endOffsetInMinutes)) for the scoreClass (HardMediumSoftScore) doesn't follow the correct pattern (999hard/999medium/999soft): the suffixedScoreTokens length (1) differs from the levelSuffixes length (3 or 4).

	at ai.timefold.solver.core.impl.score.ScoreUtil.parseScoreTokens(ScoreUtil.java:39)
	at ai.timefold.solver.core.api.score.buildin.hardmediumsoft.HardMediumSoftScore.parseScore(HardMediumSoftScore.java:31)
	at ai.timefold.solver.core.impl.score.buildin.HardMediumSoftScoreDefinition.parseScore(HardMediumSoftScoreDefinition.java:47)
	at ai.timefold.solver.core.impl.score.buildin.HardMediumSoftScoreDefinition.parseScore(HardMediumSoftScoreDefinition.java:10)
	at ai.timefold.solver.benchmark.impl.statistic.subsingle.pickedmovetypestepscore.PickedMoveTypeStepScoreDiffSubSingleStatistic.createPointFromCsvLine(PickedMoveTypeStepScoreDiffSubSingleStatistic.java:88)
	at ai.timefold.solver.benchmark.impl.statistic.subsingle.pickedmovetypestepscore.PickedMoveTypeStepScoreDiffSubSingleStatistic.createPointFromCsvLine(PickedMoveTypeStepScoreDiffSubSingleStatistic.java:36)
	at ai.timefold.solver.benchmark.impl.statistic.SubSingleStatistic.readCsvStatisticFile(SubSingleStatistic.java:168)
	at ai.timefold.solver.benchmark.impl.statistic.SubSingleStatistic.unhibernatePointList(SubSingleStatistic.java:184)
	at ai.timefold.solver.benchmark.impl.report.BenchmarkReport.writeReport(BenchmarkReport.java:252)
	at ai.timefold.solver.benchmark.impl.DefaultPlannerBenchmark.benchmarkingEnded(DefaultPlannerBenchmark.java:297)
	at ai.timefold.solver.benchmark.impl.DefaultPlannerBenchmark.benchmark(DefaultPlannerBenchmark.java:85)
```
In the following screenshot you can see that in the csvLine Arraylist has an entry for each variable effected by the cartesian product move. But getting the score is hardcoded to csvLine.get(2) that returns the String `job.endOffestInMinutes` leading to the exception during parsing of the score.

<img width="903" alt="Screenshot 2023-10-23 at 14 06 36" src="https://github.com/TimefoldAI/timefold-solver/assets/5698824/8572b88e-51f3-4e4b-9f77-bf85f144c89f">

**Expected behavior**
Getting a benchmark report.

**Actual behavior**
Creating the benchmark report leads to an exception and no report is generated.

**To Reproduce**

1. Create a Planning Entity with two PlanningVariables (In my case the planning variables are in two different Classe. The base class Job own the PlanningVariable device and the SpecialJob class that inherits from Job owns the PlanningVariable endOffsetInMinutes. Maybe that matters)
2. Create a CartesianProduct Swap Move Selector changing both variables
3. Start Benchmarking

## Environment

**0.8.41**: 

**Output of java -version**
```
openjdk version "17.0.8.1" 2023-08-22 LTS
OpenJDK Runtime Environment Corretto-17.0.8.8.1 (build 17.0.8.1+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.8.8.1 (build 17.0.8.1+8-LTS, mixed mode, sharing)
```

**Output of `uname -a` or `ver`:**
```
Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64
```

**Comment by triceo** [comment]
Thanks for reporting, @jason076!
I'll look into it when time permits.

**Comment by jason076** [comment]
Thank you for looking into it. I have upgraded to 1.3 and the problem is gone.
