### ISSUE TITLE
Feat: Android support for loading SolverConfig from XML

### ISSUE THREAD

**Issue by marinier** [TimefoldAI/timefold-solver#500]
**Is your feature request related to a problem? Please describe.**

I just tried running the Timefold 1.5.0 NQueens example in an Android app. I modified the example a little, but it works (at least on API 34, which is the most recent). The only real problem I ran into was loading the solver config from XML. This uses jaxb, which doesn't seem to work on Android (see exception below). Creating the configuration with the Java API worked fine.

It looks like the specific issue is that jaxb is using the module system, which Android doesn't support.
```
java.lang.NoSuchMethodError: No virtual method getModule()Ljava/lang/Module; in class Ljava/lang/Class; or its super classes (declaration of 'java.lang.Class' appears in /apex/com.android.art/javalib/core-oj.jar)
    at org.glassfish.jaxb.runtime.v2.MUtils.open(MUtils.java:31)
    at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:52)
    at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:44)
    at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:373)
    at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:605)
    at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:546)
    at ai.timefold.solver.core.impl.io.jaxb.GenericJaxbIO.<init>(GenericJaxbIO.java:76)
    at ai.timefold.solver.core.impl.io.jaxb.GenericJaxbIO.<init>(GenericJaxbIO.java:68)
    at ai.timefold.solver.core.impl.io.jaxb.SolverConfigIO.<init>(SolverConfigIO.java:12)
    at ai.timefold.solver.core.config.solver.SolverConfig.createFromXmlReader(SolverConfig.java:199)
    at ai.timefold.solver.core.config.solver.SolverConfig.createFromXmlInputStream(SolverConfig.java:174)
    at ai.timefold.solver.core.config.solver.SolverConfig.createFromXmlResource(SolverConfig.java:114)
    at ai.timefold.solver.core.config.solver.SolverConfig.createFromXmlResource(SolverConfig.java:89)
    at ai.timefold.solver.core.api.solver.SolverFactory.createFromXmlResource(SolverFactory.java:39)
   ... application code
```

**Describe the solution you'd like**
I suspect getting jaxb working on Android would be hard. I wonder if an alternative library could be used instead, like jackson. I've used jackson on android (mostly with YAML files) and it works fine.

**Describe alternatives you've considered**
I did some googling to see if anyone had a solution to the exception I ran into but didn't find anything. I tried forcing a downgrade to jaxb 3.0.2 like this in the gradle:

```
    implementation("ai.timefold.solver:timefold-solver-core:1.5.0") {
        exclude(group = "org.glassfish.jaxb")
        exclude(group = "jakarta.activation")
        exclude(group = "jakarta.xml.bind")
    }
    implementation("org.glassfish.jaxb:jaxb-runtime:3.0.2")
```

But that caused a different exception -- apparently jaxb wants to use AWT for some reason, which is not available on Android:

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Image;
    at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:337)
    at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:31)
    at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:91)
    at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:46)
    at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:119)
    at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:55)
    at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:403)
    at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:251)
    at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:77)
    at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1111)
    at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:140)
    at java.lang.reflect.Method.invoke(Native Method)
    at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:274)
    at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:263)
    at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:395)
    at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
    at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
    at ai.timefold.solver.core.impl.io.jaxb.GenericJaxbIO.<init>(GenericJaxbIO.java:76)
    at ai.timefold.solver.core.impl.io.jaxb.GenericJaxbIO.<init>(GenericJaxbIO.java:68)
    at ai.timefold.solver.core.impl.io.jaxb.SolverConfigIO.<init>(SolverConfigIO.java:12)
    at ai.timefold.solver.core.config.solver.SolverConfig.createFromXmlReader(SolverConfig.java:199)
    at ai.timefold.solver.core.config.solver.SolverConfig.createFromXmlInputStream(SolverConfig.java:174)
    at ai.timefold.solver.core.config.solver.SolverConfig.createFromXmlResource(SolverConfig.java:114)
    at ai.timefold.solver.core.config.solver.SolverConfig.createFromXmlResource(SolverConfig.java:89)
    at ai.timefold.solver.core.api.solver.SolverFactory.createFromXmlResource(SolverFactory.java:39)
... application code

```
**Additional context**

Here's the code for reference. I used Android Studio Hedgehog and used one of the built-in templates to create a basic app. The code that touches timefold is in `app/src/main/java/timefoldandroidtest/timefoldandroidtest/FirstFragment.java`. The slightly modified NQueens code is in `app/src/main/java/ai...`. The modifications were removing stuff related to persistence, the main methods, etc.

[TimefoldAndroidTest.zip](https://github.com/TimefoldAI/timefold-solver/files/13688545/TimefoldAndroidTest.zip)

**Comment by triceo** [comment]
Hello, @marinier!

First of all, thanks for taking the time to report this issue. Unfortunately, not supporting Android is a conscious decision on our part, made a long time ago. Our decision was primarily driven by the fact that we do not see the merit of running a CPU-bound workloads such as Timefold Solver on a mobile device.

One of the secondary factors in our decision making was that the selective Java API support within Android would place unacceptable restrictions on the libraries and technologies which we may want to use. (Case in point: At the time the decision was made, the ecosystem was moving to Java 17, which was not supported by Android and no indication was made as to if/when that support would come, or how much of Java 17 they'd choose to support.) The fact that pretty standard Java libraries (such as JAXB) are not supported on Android only serves to reinforce that view.

To help with the use case you mention, I suggest:

- Do not use the XML config. The solver can just as well be configured with plain Java, see `SolverConfig`.
- The `examples` app has a lot of boilerplate which is not necessary for the solver to run. You'd be better off starting from the [Hello World quickstart](https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/hello-world), which is paired to the bone and therefore has the biggest chance to work on Android.
- Most importantly, my suggestion is to have Android as a thin client only, and have your actual solver run somewhere else as a remote service. The [Employee Scheduling quickstart](https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/use-cases/employee-scheduling) shows you how to turn the solver into a web application with an exposed REST API.

I am open to merging PRs which make minimal changes to the codebase in order to make the experience on Android better, if you want to provide them. But refactoring entire subsystems of the solver (such as the config) for the sake of Android is not on the agenda.

**Comment by marinier** [comment]
I understand where you're coming from, and given it works using the Java API for configuration it certainly sounds like this isn't worth the effort.

FWIW, my use case involves situations where there is no internet access and the optimization problems are small (it typically only takes a few seconds for timefold to find a solution). So even without official support I still intend to use this on Android. I'll let you know if changes get introduced that cause problems that I can't work around.
