### ISSUE TITLE
Score corruption analysis fails with ClassCastException because MatchAnalysis doesn

### ISSUE THREAD

**Issue by thimmwork** [TimefoldAI/timefold-solver#526]
**Describe the bug**
This probably wasn't detected earlier because it only occurs on actual score corruption:
When appending the analysis, the scoreDirector performs an unparameterized `Set<MatchAnalysis>.stream().sorted()` which would require MatchAnalysis to implement Comparable, but it doesn't.

**Expected behavior**
The score analysis should not fail.
The actually intended behavior is debatable. I'll provide a PR that removes sorting.
I assume that the sorting won't bring much value when analyzing the corruption, because you have to compare the sets of excess and missing constraint matches anyway.
Feel free to suggest otherwise.

**Actual behavior**
a `ClassCastException` is thrown with a stacktrace like this:
```
java.lang.ClassCastException: class ai.timefold.solver.core.api.score.analysis.MatchAnalysis cannot be cast to class java.lang.Comparable (ai.timefold.solver.core.api.score.analysis.MatchAnalysis is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')

	at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1308)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.appendAnalysis(AbstractScoreDirector.java:826)
	at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.buildScoreCorruptionAnalysis(AbstractScoreDirector.java:788)
	at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.assertScoreFromScratch(AbstractScoreDirector.java:670)
	at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.assertWorkingScoreFromScratch(AbstractScoreDirector.java:652)
	at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.assertExpectedUndoMoveScore(AbstractScoreDirector.java:693)
	at ai.timefold.solver.core.impl.localsearch.decider.LocalSearchDecider.doMove(LocalSearchDecider.java:123)
	at ai.timefold.solver.core.impl.localsearch.decider.LocalSearchDecider.decideNextStep(LocalSearchDecider.java:97)
	at ai.timefold.solver.core.impl.localsearch.DefaultLocalSearchPhase.solve(DefaultLocalSearchPhase.java:72)
	at ai.timefold.solver.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:82)
	at ai.timefold.solver.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:193)
```

**To Reproduce**
Run the solver with FAST_ASSERT and a corrupted score.

## Environment

**Timefold Solver Version or Git ref**: 
1.5.0

**Output of `java -version`:**
openjdk 21.0.1 2023-10-17
OpenJDK Runtime Environment GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

**Output of `uname -a` or `ver`:**
Darwin WYJTH5W7YK 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

## Additional information
I'll be happy to provide a PR, though I'll still have to figure out the best way to test this.

**Comment by triceo** [comment]
Nice catch, @thimmwork!

> I'll be happy to provide a PR, though I'll still have to figure out the best way to test this.

That'll be appreciated. I'm currently thinking what would be the best fix.

1. We could remove sorting from the stream. However, the sorting is there to maintain consistent order of matches for people to be able to compare the exception messages to other messages.
2. We could make `MatchAnalysis` implement `Comparable`; first by `ConstraintRef`, then by `Score` and optionally by `ConstraintJustification` if `implements Comparable`. Finally, all of that being equal, we can compare by identity hashcode, to make a complete ordering?
3. We could do 2, but not through implementing `Comparable`, but by adding a comparator to the stream in question. This allows us to solve the problem of ordering matches, without imposing any particular ordering for the data type.

I'm not in favor of 1. I could see us doing either 2 or 3. WDYT?

**Comment by thimmwork** [comment]
Hi @triceo ,
thanks for the quick reply.
The code line in question seems to be the only situation where a sorting over MatchAnalysis objects is performed. 
If you want to keep the sorting, I'd favor 2 over 3. Adding a Comparator for only a single use seems over-engineered, and the fact that it accesses all properties indicates it is tightly coupled to the implementation of MatchAnalysis anyway.

**Comment by triceo** [comment]
The reason why I even suggested 3 is that 2 means this behavior becomes public API, set in stone forever. I'm always reluctant to do that without a clear use case that can not be satisfied in other ways.

That said, you're right - it is tightly coupled to the implementation, it uses all the fields, so I can't see why or how we would (at some point in the future) want to do something else with it.

So, let's do 2, and mention it in `MatchAnalysis` javadoc.

When it comes to testing, score corruptions are notoriously hard to test. Unless you want to do a whole lot of mocking on the score director and associated classes, you'll have to recreate a situation in which the exception would be thrown. Probably from the outside of `ScoreDirector`.
Which is likely why this part of the code was not tested in the first place. :-(

**Comment by thimmwork** [comment]
I managed to write a test that triggers the code block in question. I noticed that the exception only occurs when there's more than one element in the excessSet or missingSet, because sorting is skipped on streams with one element.
However, the test is messy. And it would probably cause more maintenance effort than benefit. So I'll exclude it from the PR, but you can use it to verify before/after behavior.

PR: https://github.com/TimefoldAI/timefold-solver/pull/527

```
package ai.timefold.solver.core.impl.score;

import ai.timefold.solver.core.api.score.buildin.simple.SimpleScore;
import ai.timefold.solver.core.api.score.calculator.ConstraintMatchAwareIncrementalScoreCalculator;
import ai.timefold.solver.core.api.score.calculator.IncrementalScoreCalculator;
import ai.timefold.solver.core.api.score.constraint.ConstraintMatch;
import ai.timefold.solver.core.api.score.constraint.ConstraintMatchTotal;
import ai.timefold.solver.core.api.score.constraint.ConstraintRef;
import ai.timefold.solver.core.api.score.constraint.Indictment;
import ai.timefold.solver.core.api.score.stream.ConstraintJustification;
import ai.timefold.solver.core.config.score.director.ScoreDirectorFactoryConfig;
import ai.timefold.solver.core.config.solver.EnvironmentMode;
import ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor;
import ai.timefold.solver.core.impl.score.director.InnerScoreDirectorFactory;
import ai.timefold.solver.core.impl.score.director.ScoreDirectorFactoryFactory;
import ai.timefold.solver.core.impl.testdata.domain.TestdataValue;
import ai.timefold.solver.core.impl.testdata.domain.shadow.corrupted.TestdataCorruptedShadowedEntity;
import ai.timefold.solver.core.impl.testdata.domain.shadow.corrupted.TestdataCorruptedShadowedSolution;
import org.junit.jupiter.api.Test;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.fail;

public class ScoreDirectorAnalysisTest {
    private static ConstraintRef constraintRef1 = new ConstraintRef(ScoreDirectorAnalysisTest.class.getPackageName(), "constraint1", "ai.timefold.solver.core.impl.score/constraint1");
    private static ConstraintRef constraintRef2 = new ConstraintRef(ScoreDirectorAnalysisTest.class.getPackageName(), "constraint2", "ai.timefold.solver.core.impl.score/constraint2");

    private final SolutionDescriptor<TestdataCorruptedShadowedSolution> solutionDescriptor =
            TestdataCorruptedShadowedSolution.buildSolutionDescriptor();

    protected InnerScoreDirectorFactory<TestdataCorruptedShadowedSolution, SimpleScore>
    buildInnerScoreDirectorFactory(SolutionDescriptor<TestdataCorruptedShadowedSolution> solutionDescriptor) {
        ScoreDirectorFactoryConfig scoreDirectorFactoryConfig = new ScoreDirectorFactoryConfig()
                .withIncrementalScoreCalculatorClass(TestdataCorruptedShadowedIncrementalScoreCalculator.class);
        ScoreDirectorFactoryFactory<TestdataCorruptedShadowedSolution, SimpleScore> scoreDirectorFactoryFactory =
                new ScoreDirectorFactoryFactory<>(scoreDirectorFactoryConfig);
        return scoreDirectorFactoryFactory.buildScoreDirectorFactory(getClass().getClassLoader(),
                EnvironmentMode.FAST_ASSERT, solutionDescriptor);
    }

    @Test
    void analyis_of_corrupted_score_should_return_corruption_hints() {
        var factory = buildInnerScoreDirectorFactory(this.solutionDescriptor);
        var scoreDirector = factory.buildScoreDirector(true, true);


        var solution = new TestdataCorruptedShadowedSolution("code");
        var value = new TestdataValue("123");
        solution.setEntityList(List.of(new TestdataCorruptedShadowedEntity("code1", value, 0)));
        solution.setValueList(List.of(value));
        solution.setScore(SimpleScore.ONE);
        scoreDirector.setWorkingSolution(solution);

        try {
            scoreDirector.assertWorkingScoreFromScratch(SimpleScore.ONE, null);
            fail("expected exception caused by detected score corruption");
        } catch (IllegalStateException e) {
            //expected
        }
    }

    public static class TestdataCorruptedShadowedIncrementalScoreCalculator implements
            IncrementalScoreCalculator<TestdataCorruptedShadowedSolution, SimpleScore>,
            ConstraintMatchAwareIncrementalScoreCalculator<TestdataCorruptedShadowedSolution, SimpleScore> {

        private TestdataCorruptedShadowedSolution solution;

        public TestdataCorruptedShadowedIncrementalScoreCalculator() {
        }

        @Override
        public void resetWorkingSolution(TestdataCorruptedShadowedSolution workingSolution) {
            this.solution = workingSolution;
        }

        @Override
        public void beforeEntityAdded(Object entity) {
        }

        @Override
        public void afterEntityAdded(Object entity) {
        }

        @Override
        public void beforeVariableChanged(Object entity, String variableName) {
        }

        @Override
        public void afterVariableChanged(Object entity, String variableName) {
        }

        @Override
        public void beforeEntityRemoved(Object entity) {
        }

        @Override
        public void afterEntityRemoved(Object entity) {
        }

        @Override
        public SimpleScore calculateScore() {
            return SimpleScore.ZERO;
        }

        @Override
        public void resetWorkingSolution(TestdataCorruptedShadowedSolution workingSolution, boolean constraintMatchEnabled) {
            this.solution = workingSolution;
        }

        @Override
        public Collection<ConstraintMatchTotal<SimpleScore>> getConstraintMatchTotals() {
            return List.of(new SimpleScoreConstraintMatchTotal(constraintRef1), new SimpleScoreConstraintMatchTotal(constraintRef2));
        }

        @Override
        public Map<Object, Indictment<SimpleScore>> getIndictmentMap() {
            return Map.of();
        }


        private class SimpleScoreConstraintMatchTotal implements ConstraintMatchTotal<SimpleScore> {

            private final ConstraintRef constraintRef;

            private ConstraintJustification justification = new ConstraintJustification() {
            };

            public SimpleScoreConstraintMatchTotal(ConstraintRef constraintRef) {
                this.constraintRef = constraintRef;
            }

            @Override
            public ConstraintRef getConstraintRef() {
                return this.constraintRef;
            }

            @Override
            public SimpleScore getConstraintWeight() {
                return SimpleScore.ONE;
            }

            @Override
            public Set<ConstraintMatch<SimpleScore>> getConstraintMatchSet() {
                List<Object> entityList = (List) solution.getEntityList();
                return Set.of(new ConstraintMatch<SimpleScore>(constraintRef1, justification, entityList, SimpleScore.of(6)),
                        new ConstraintMatch<>(constraintRef2, justification, List.of(), SimpleScore.of(7)));
            }

            @Override
            public SimpleScore getScore() {
                return SimpleScore.ZERO;
            }

            @Override
            public String toString() {
                return "SimpleScoreConstraintMatchTotal{" +
                        "constraintRef1=" + getConstraintRef() +
                        ", constraintRef2=" + getScore() +
                        ", justification=" + justification +
                        '}';
            }
        }
    }
}
```
