### ISSUE TITLE
Score Corruption in Construction Heuristic is not shown correctly in the log

### ISSUE THREAD

**Issue by simontiffert** [TimefoldAI/timefold-solver#529]
A score corruption detected by FULL_ASSERT in the Construction Heuristics is not shown correctly in the log and returns java.lang.IllegalArgumentException: Cannot analyze solution.

**Expected behavior**
A score corruption with FULL_ASSERT set to true displays a score corruption in the log showing the difference between current score and the actual score.

**Actual behavior**

The solution is not yet fully initialized (CH) and the solvers stopps with a misleading exception `java.lang.IllegalArgumentException: Cannot analyze solution` in the middle of solving.

*Log Entry*
```
2023-12-28 15:29:23,409 ERROR [org.acm.sch.res.TimetableResource] (pool-8-thread-1) Failed solving jobId (336bc5dc-58aa-4991-aed2-9eec3d3c1dab).: java.lang.IllegalArgumentException: Cannot analyze solution (org.acme.schooltimetabling.domain.Timetable@1a1df9e2) as it is not initialized (-36init/-7hard/0soft).
Maybe run the solver first?
        at ai.timefold.solver.core.impl.score.director.InnerScoreDirector.buildScoreAnalysis(InnerScoreDirector.java:460)
        at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.buildScoreCorruptionAnalysis(AbstractScoreDirector.java:669)
        at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.assertScoreFromScratch(AbstractScoreDirector.java:616)
        at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.assertWorkingScoreFromScratch(AbstractScoreDirector.java:598)
        at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.doAndProcessMove(AbstractScoreDirector.java:200)
        at ai.timefold.solver.core.impl.constructionheuristic.decider.ConstructionHeuristicDecider.doMove(ConstructionHeuristicDecider.java:115)
        at ai.timefold.solver.core.impl.constructionheuristic.decider.ConstructionHeuristicDecider.decideNextStep(ConstructionHeuristicDecider.java:89)
        at ai.timefold.solver.core.impl.constructionheuristic.DefaultConstructionHeuristicPhase.solve(DefaultConstructionHeuristicPhase.java:48)
        at ai.timefold.solver.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:83)
        at ai.timefold.solver.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:193)
        at ai.timefold.solver.core.impl.solver.DefaultSolverJob.call(DefaultSolverJob.java:110)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

**To Reproduce**
- Set to FULL_ASSERT
- Generate a score corruption in the Construction Heuristic e.g. in the TimetableConstraintProvider.java
- Start the solver

See https://github.com/simontiffert/timefold-quickstarts/commit/373d2d9c55b9fcaf93d002f592e40ff406d97c3e

``` import java.time.Duration;
+import java.util.Random;
 
 import ai.timefold.solver.core.api.score.buildin.hardsoft.HardSoftScore;
 import ai.timefold.solver.core.api.score.stream.Constraint;
@@ -41,7 +42,7 @@
                         // ... in the same room ...
                         Joiners.equal(Lesson::getRoom))
                 // ... and penalize each pair with a hard weight.
-                .penalize(HardSoftScore.ONE_HARD)
+                .penalize(HardSoftScore.ONE_HARD, (x,y) -> new Random().nextInt(10))
                 .justifyWith((lesson1, lesson2, score) -> new RoomConflictJustification(lesson1.getRoom(), lesson1.getId(), lesson2.getId()))
                 .asConstraint("Room conflict");
     }
```

**Comment by triceo** [comment]
Thanks for reporting, @simontiffert! We'll look into it.

**Comment by triceo** [comment]
I understand what's going on. We'll fix it next week for 1.6.0, tentatively planned for week 2 of 2024.
