### ISSUE TITLE
Upgrading Quarkus project to 3.6.4 from 3.4.2 fails on ai.timefold.solver.quarkus.deployment.TimefoldProcessor steps loading

### ISSUE THREAD

**Issue by zeppelinux** [TimefoldAI/timefold-solver#554]
I have a  Quarkus project that was recently ported from Optaplanner to Timefold, when I'm trying to upgrade quarkus version to 3.6.4  it fails with exception at the start:

```
2024-01-08 16:09:27,245 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: Failed to load steps from class ai.timefold.solver.quarkus.deployment.TimefoldProcessor
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:164)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:112)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:433)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.NoClassDefFoundError: io/quarkus/devconsole/spi/DevConsoleRuntimeTemplateInfoBuildItem
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
        at io.quarkus.deployment.ExtensionLoader.getMethods(ExtensionLoader.java:922)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFromClass(ExtensionLoader.java:432)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:162)
```

**Comment by triceo** [comment]
Hello @zeppelinux, thanks for reporting!
Can you please share your version of Timefold Solver?

Timefold Solver 1.5.0 uses Quarkus 3.6, and we will likely release Timefold Solver 1.6.0 this week that will bring the latest Quarkus.

**Comment by zeppelinux** [comment]
Hi @triceo, sounds good!

I'm not specifying the Timefold version in the pom, so Quarkus version  drives it. 
I see timefold-solver-quarkus 1.2.0 for Quarkus 3.4.2 and the same timefold-solver-quarkus 1.2.0 for Quarkus 3.6.4 though

Thanks!

**Comment by triceo** [comment]
Timefold Solver 1.2 is not compatible with Quarkus 3.6. (There were hard breaks in the dev console on the Quarkus side, which is the exception you're seeing.) New versions of Timefold Solver already adapted to this change on Quarkus side, so they should work just fine.

Please reopen if that's not the case.
