### ISSUE TITLE
It fails to create list planning variable entity descriptor with `java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to class java.lang.Class`

### ISSUE THREAD

**Issue by holgerbrandl** [TimefoldAI/timefold-solver#832]
Consider the kotlin example from https://gist.github.com/holgerbrandl/df80f0f13b93afec5cfa8d3518da8db4 

When computing the entity descriptor of the list planning variable `Room.roomSchedule` it fails with

```
Exception in thread "main" java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.WildcardTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')
	at ai.timefold.solver.core.impl.domain.variable.descriptor.GenuineVariableDescriptor.lambda$findAnonymousValueRangeMemberAccessors$2(GenuineVariableDescriptor.java:120)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at ai.timefold.solver.core.impl.domain.variable.descriptor.GenuineVariableDescriptor.findAnonymousValueRangeMemberAccessors(GenuineVariableDescriptor.java:131)
```

Tested with tf 1.9

**Comment by triceo** [comment]
Thanks for reporting, @holgerbrandl! We'll take a look when time permits.

**Comment by triceo** [comment]
I'm not exactly sure why this is failing, but using a raw type `List` instead of `List<Course>` could be a workaround. Another possible workaround would be to actually provide the value range reference ID, as that may circumvent the auto-detection which is the problem here.

**Comment by holgerbrandl** [comment]
Thanks @triceo for the great advice. Adding the range ref id avoids the problem. 

I've updated the gist accordingly.
