### ISSUE TITLE
Blueprint Benchmark fails if configurations are not supported

### ISSUE THREAD

**Issue by simontiffert** [TimefoldAI/timefold-solver#930]
**Describe the bug**
The blueprint benchmark fails if one of its configuration fails.

**Expected behavior**
The blueprint benchmark runs all feasible benchmarks and marks the others as failed and generates a report.

**Actual behavior**
The benchmark stops at the first issue with the error message: 

`
java.lang.NullPointerException: Cannot invoke "ai.timefold.solver.benchmark.impl.SubSingleBenchmarkRunner.getRandomSeed()" because "subSingleBenchmarkRunner" is null
	at ai.timefold.solver.benchmark.impl.DefaultPlannerBenchmark.warmUp(DefaultPlannerBenchmark.java:220)
	at ai.timefold.solver.benchmark.impl.DefaultPlannerBenchmark.warmUp(DefaultPlannerBenchmark.java:150)
	at ai.timefold.solver.benchmark.impl.DefaultPlannerBenchmark.benchmark(DefaultPlannerBenchmark.java:83)
	at ai.timefold.solver.benchmark.impl.DefaultPlannerBenchmark.benchmarkAndShowReportInBrowser(DefaultPlannerBenchmark.java:410)
	at org.acme.vehiclerouting.solver.BenchmarkTest.benchmark(BenchmarkTest.java:20)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1017)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:831)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.IllegalArgumentException: Construction Heuristic phase with a list variable does not support constructionHeuristicType configuration. Remove the constructionHeuristicType (FIRST_FIT) from the config.
		at ai.timefold.solver.core.impl.constructionheuristic.DefaultConstructionHeuristicPhaseFactory.failIfConfigured(DefaultConstructionHeuristicPhaseFactory.java:130)
		at ai.timefold.solver.core.impl.constructionheuristic.DefaultConstructionHeuristicPhaseFactory.findValidListVariableDescriptor(DefaultConstructionHeuristicPhaseFactory.java:122)
		at ai.timefold.solver.core.impl.constructionheuristic.DefaultConstructionHeuristicPhaseFactory.buildDefaultEntityPlacerConfig(DefaultConstructionHeuristicPhaseFactory.java:111)
		at ai.timefold.solver.core.impl.constructionheuristic.DefaultConstructionHeuristicPhaseFactory.lambda$buildPhase$0(DefaultConstructionHeuristicPhaseFactory.java:68)
		at java.base/java.util.Optional.orElseGet(Optional.java:364)
		at ai.timefold.solver.core.impl.constructionheuristic.DefaultConstructionHeuristicPhaseFactory.buildPhase(DefaultConstructionHeuristicPhaseFactory.java:68)
		at ai.timefold.solver.core.impl.constructionheuristic.DefaultConstructionHeuristicPhaseFactory.buildPhase(DefaultConstructionHeuristicPhaseFactory.java:40)
		at ai.timefold.solver.core.impl.phase.PhaseFactory.buildPhases(PhaseFactory.java:59)
		at ai.timefold.solver.core.impl.solver.DefaultSolverFactory.buildPhaseList(DefaultSolverFactory.java:249)
		at ai.timefold.solver.core.impl.solver.DefaultSolverFactory.buildSolver(DefaultSolverFactory.java:125)
		at ai.timefold.solver.core.api.solver.SolverFactory.buildSolver(SolverFactory.java:119)
		at ai.timefold.solver.benchmark.impl.SubSingleBenchmarkRunner.call(SubSingleBenchmarkRunner.java:107)
		at ai.timefold.solver.benchmark.impl.SubSingleBenchmarkRunner.call(SubSingleBenchmarkRunner.java:27)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base/java.lang.Thread.run(Thread.java:1583)
`

**To Reproduce**
Reproducer with VehicleRouting src/test/java/org/acme/vehiclerouting/solver/BenchmarkTest.java:
https://github.com/simontiffert/timefold-quickstarts/tree/blueprintBenchmark

## Environment

**Timefold Solver Version or Git ref**: 
1.11.0

**Output of `java -version`:**
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

**Comment by triceo** [comment]
Thanks for reporting, @simontiffert!
We'll take a look.
