### ISSUE TITLE
No qualifying bean of type 'ai.timefold.solver.core.api.solver.SolverFactory<?>' available

### ISSUE THREAD

**Issue by yy306525121** [TimefoldAI/timefold-solver#952]
I am following this tutorial step by step to implement it：https://docs.timefold.ai/timefold-solver/latest/quickstart/spring-boot/spring-boot-quickstart

I have a project structure that is similar to the following:
| --- School_Project
| ----- module A (all timefold at here)
| ----- module B (starup application at here and dependency module A) 

Then it throws an error at startup:

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'solverManager' defined in class path resource [ai/timefold/solver/spring/boot/autoconfigure/TimefoldSolverBeanFactory.class]: Unsatisfied dependency expressed through method 'solverManager' parameter 0: No qualifying bean of type 'ai.timefold.solver.core.api.solver.SolverFactory<?>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:542)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785)
	... 33 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'ai.timefold.solver.core.api.solver.SolverFactory<?>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1880)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1449)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785)
	... 47 common frames omitted

**Comment by triceo** [comment]
Hello @yy306525121 and thank you for reporting.
We'll take a look when time permits.

**Comment by zepfred** [comment]
Hey @yy306525121. Module B seems to be unable to find the required classes for the autoconfiguration. 

Could you share the `pom.xml` from both projects?

**Comment by yy306525121** [comment]
> Hey @yy306525121. Module B seems to be unable to find the required classes for the autoconfiguration.
> 
> Could you share the `pom.xml` from both projects?

i'm sorry, When I try to provide a demo, I find that there are no issues, However, it reported an error in my actual project. My actual project is quite complex. Next, I will troubleshoot the issue on my own. i'm very sorry for this issue

**Comment by yy306525121** [comment]
i found the error reason
my startup application class in package "cn.iocoder.yudao.server"
but my PlanningSolution class in package "cn.iocoder.yudao.module..."

in org.springframework.boot.autoconfigure.domain.EntityScanner class the getPackages method only get package "cn.iocoder.yudao.server",  so it cannot scan my PlanningSolution， so cause the error,

i have add these packages like @SpringBootApplication(scanBasePackages = {"${yudao.info.base-package}.server", "${yudao.info.base-package}.module"}),  but it does not work, beause some reason, you can look it at： https://stackoverflow.com/questions/45343594/why-autoconfigurationpackages-not-consider-componentscan

solution:
1: move startup application to package "cn.iocoder.yudao"
2: add @AutoConfigurationPackage(basePackages = "cn.iocoder.yudao") in your startup application
