### ISSUE TITLE
Feat: produce stack trace from python code called from JVM

### ISSUE THREAD

**Issue by Alex-K37** [TimefoldAI/timefold-solver#960]
**Is your feature request related to a problem? Please describe.**
I have a generate_problem function, which  updates certain attributes of the domain objects. It seems, that this is an interaction issue of Python code executed from the JVM. 

```
Traceback (most recent call last):
  File "/home/***/git/optapy-pplan/optapy-test/src/main2.py", line 426, in <module>
    solution = solver.solve(generate_problem(sservice.context._inputfile))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.virtualenvs/timefold/lib/python3.11/site-packages/timefold/solver/_solver.py", line 109, in solve
    java_solution = self._delegate.solve(java_problem)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'ai.timefold.jpyinterpreter.types.PythonString'
```
In my opinion, such an error could surface at any point during development leaving the developer completely clueless where to look for the error, unless he/she is following an approach of add-line/solve/add-line/solve/.... which I consider the most tedious. 

**Describe the solution you'd like**

Produce an error message which includes a stack trace from python. This should include information that relates to the original code somehow, even if mangled by jpype or jpyinterpreter.

**Describe alternatives you've considered**

1) Follow an approach of add-line/solve/add-line/solve/.... which I consider the most tedious. 

2) Perform type checking after generate_problem() (does that help at all with a possibly dynamic issue?)

**Additional remarks**

I cannot find hints to why this PythonString type is necessary and which components have to use it. There is a translation of jpype between Java strings and Python strings. Why isn't this sufficient? Or, why isn't this PythonString automatically translated to a python string, while executing in CPython or jpy*-translated python code? I do not want to deviate too much from my original feature request, however.

**Comment by triceo** [comment]
As of today, Timefold halted any further development of the Python solver. 
Find out more here: https://github.com/TimefoldAI/timefold-solver/discussions/1698

Closing this issue.
