### ISSUE TITLE
TimefoldBenchmarkAutoConfiguration throws a NPE when global termination is not defined in solver config

### ISSUE THREAD

**Issue by mcimbora** [TimefoldAI/timefold-solver#97]
Hi team,

Using Timefold 0.9.39 + Spring boot starter 3.1.0.

At times, I don't specify a global termination in the solver configuration. Instead, I provide it on local-search basis only, e.g.:

```
<localSearch>
    <termination>
        <unimprovedSecondsSpentLimit>10</unimprovedSecondsSpentLimit>
    </termination>
</localSearch>
```

Adding the following dependency leads to benchmarker autoconfiguration kicking in during Spring Boot application startup.
```
<dependency>
    <groupId>ai.timefold.solver</groupId>
    <artifactId>timefold-solver-benchmark</artifactId>
    <version>${timefold.version}</version>
</dependency>
```

... which produces the exception below. The issue can be workarounded by defining a global solver termination, e.g.

```
<solver>
    <termination>
        <secondsSpentLimit>600</secondsSpentLimit>
    </termination>
```

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'plannerBenchmarkConfig' defined in class path resource [ai/timefold/solver/spring/boot/autoconfigure/TimefoldBenchmarkAutoConfiguration.class]: Failed to instantiate [ai.timefold.solver.benchmark.config.PlannerBenchmarkConfig]: Factory method 'plannerBenchmarkConfig' threw exception with message: Cannot invoke "ai.timefold.solver.core.config.solver.SolverConfig.getTerminationConfig()" because the return value of "ai.timefold.solver.benchmark.config.SolverBenchmarkConfig.getSolverConfig()" is null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294)
	at com.xxx.planning.xxxApplication.main(xxxApplication.java:10)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [ai.timefold.solver.benchmark.config.PlannerBenchmarkConfig]: Factory method 'plannerBenchmarkConfig' threw exception with message: Cannot invoke "ai.timefold.solver.core.config.solver.SolverConfig.getTerminationConfig()" because the return value of "ai.timefold.solver.benchmark.config.SolverBenchmarkConfig.getSolverConfig()" is null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	... 19 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "ai.timefold.solver.core.config.solver.SolverConfig.getTerminationConfig()" because the return value of "ai.timefold.solver.benchmark.config.SolverBenchmarkConfig.getSolverConfig()" is null
	at ai.timefold.solver.spring.boot.autoconfigure.TimefoldBenchmarkAutoConfiguration.plannerBenchmarkConfig(TimefoldBenchmarkAutoConfiguration.java:94)
	at ai.timefold.solver.spring.boot.autoconfigure.TimefoldBenchmarkAutoConfiguration$$SpringCGLIB$$0.CGLIB$plannerBenchmarkConfig$0(<generated>)
	at ai.timefold.solver.spring.boot.autoconfigure.TimefoldBenchmarkAutoConfiguration$$SpringCGLIB$$2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at ai.timefold.solver.spring.boot.autoconfigure.TimefoldBenchmarkAutoConfiguration$$SpringCGLIB$$0.plannerBenchmarkConfig(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 20 common frames omitted
```

**Comment by triceo** [comment]
Thanks for reporting! I'll take a look when time permits.

**Comment by mcimbora** [comment]
Thanks :-)

**Comment by triceo** [comment]
Actually if you could provide a small Maven project that I could use to reproduce it, that would be welcome. My first attempt did not succeed.

**Comment by mcimbora** [comment]
@triceo Sure, there you go https://github.com/mcimbora/timefold-reproducers/tree/reproducer/issue_97
